### ISSUE TITLE
Top-level list item markers are clipped off on small screens

### ISSUE THREAD

**Issue by knowler** [kizu/kizu-blog#7]
I’m using an iPhone 13 Pro running iOS 17.1 and the top-level list items seem like they need some `padding-inline-start` applied so their markers don’t get clipped off. I’m unable to test on desktop, but I’d be happy do so and update the issue when I have the opportunity.

![Screenshot of a blog post in Safari where there is a multi-level list. The top-level item bullets are only partially visible on the left hand side of the screen. Their text content horizontally aligns with regular paragraph content.](https://github.com/kizu/kizu-blog/assets/6908001/77cb9c2e-d2fa-4601-b71f-21ce97a85c8b)

**Comment by kizu** [comment]
Thanks for the report! It should be fixed now :)
